[package]
name = "dbtest"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
sqlx = { version = "0.4.0-beta.1", default-features = false, features = ["runtime-tokio", "postgres", "tls"] }
tokio = { version = "0.2.1" }